name: Auto-Merge Dependabot PRs

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  auto_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR is from Dependabot
        id: dependabot
        run: echo ::set-output name=IS_DEPENDABOT::$(jq -r '.sender.login == "dependabot[bot]"' $GITHUB_EVENT_PATH)

      - name: Auto-Merge PR
        if: steps.dependabot.outputs.IS_DEPENDABOT == 'true'
        run: |
          pr_number=$(jq -r ".pull_request.number" "$GITHUB_EVENT_PATH")
          repo_name=$(basename -s .git `git config --get remote.origin.url`)
          curl -X PUT \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/pulls/$pr_number/merge"
